# 1. CONFIGURAÇÃO DO BACKEND (Firebase)
backend:
  name: firebase
  # Configurações de autenticação e conexão com o Firebase
  auth_type: "firebase"
  config:
    apiKey: "AIzaSyC2cBfkKjT16srTeVYAedNgA6qOw0h97vc"
    authDomain: "yb-make.firebaseapp.com"
    projectId: "yb-make"
    storageBucket: "yb-make.firebasestorage.app"
    appId: "1:685414342925:web:9b17e3194f393c87569044"

# 2. CONFIGURAÇÕES GLOBAIS
locale: "pt"
publish_mode: editorial_workflow

# 3. CONFIGURAÇÕES DE MÍDIA
# O backend do Firebase não usa media_folder, ele fará upload para o Firebase Storage.
media_folder: "imagens/uploads"
public_folder: "imagens/uploads"

# 4. COLEÇÕES DE DADOS
collections:
  - name: "products"
    label: "Produtos"
    folder: "products" # O nome da coleção no Firestore
    create: true # Permite criar novos produtos
    slug: "{{fields.title}}"
    fields:
      - {label: "Nome do Produto", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Preço", name: "price", widget: "number"}
      - {label: "Imagem do Produto", name: "image", widget: "image"}