backend:
  name: firebase
  # A chave "branch" não é usada pelo backend do Firebase e pode ser removida.
  # O backend do Firebase salva as imagens no Firebase Storage.
  # As configurações abaixo são as corretas para o Firebase.
  api_key: "AIzaSyC2cBfkKjT16srTeVYAedNgA6qOw0h97vc"
  auth_domain: "yb-make.firebaseapp.com"
  project_id: "yb-make"
  use_json: true

locale: "pt" # Define o idioma para português do Brasil

publish_mode: editorial_workflow

# A pasta de mídia não é necessária, pois o Firebase Storage será usado.

collections:
  - name: "products"
    label: "Produtos"
    folder: "products" # Nome da coleção no Firestore onde os produtos são salvos.
    create: true
    slug: "{{fields.title}}"
    fields:
      - {label: "Nome do Produto", name: "title", widget: "string"}
      - {label: "Descrição", name: "description", widget: "text"}
      - {label: "Preço", name: "price", widget: "number"}
      - {label: "Imagem do Produto", name: "image", widget: "image"}